services:
  growapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: grow-docker
    container_name: growapp
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      PORT: ${PORT}

  db:
    image: mysql:latest
    container_name: mysql-grow
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
